FROM python:3.6.0-alpine
MAINTAINER Alexander Puzynia <werwolf.by@gmail.com>

COPY monitorrent/requirements.txt /var/www/monitorrent/requirements.txt
RUN pip install --no-cache-dir -r /var/www/monitorrent/requirements.txt
RUN pip install PySocks
COPY monitorrent /var/www/monitorrent

WORKDIR /var/www/monitorrent

EXPOSE 6687

CMD ["python", "server.py"]
